### ISSUE TITLE
add a high-level, easy to use `read_parquet`

### ISSUE THREAD

**Issue by xiaodaigh** [JuliaIO/Parquet.jl#100]
One should be able to `DataFrame!(read_parquet(path))` to read a parquet instead of the convoluted BatchCursor way right now.

**Comment by quinnj** [comment]
Yes, this would be great; happy to chat about Tables.jl source API implementation if that would help.

**Comment by sa-** [comment]
Is there a way to do this right now? I can't quite figure out how to do it without using RecordCursor

**Comment by sa-** [comment]
`pyarrow.parquet.read_table(...)` can be used as a benchmark. I've been trying to find something faster than the `BatchedColumnsCursor` approach but it's not the easiest thing to do.

**Comment by xiaodaigh** [comment]
done first version in #116
