### ISSUE TITLE
overloading of Base.eltype

### ISSUE THREAD

**Issue by mfz** [JuliaIO/Parquet.jl#107]
Hello!

Thank you for developing Parquet.jl!

Trying to incorporate parquet files in to a package, 
I realized that you overload Base.eltype on instances instead of types.

i.e. you do
`eltype(cursor::RecordCursor{T}) where {T} = T`

instead of
`eltype(::Type{RecordCursor{T}}) where {T} = T`

as stipulated in Julia documentation.

best,
Florian

**Comment by tanmaykm** [comment]
Thanks for pointing out. Should be fixed by #117
