### ISSUE TITLE
"UndefVarError: File not defined" when trying to use Parquet.File

### ISSUE THREAD

**Issue by sa-** [JuliaIO/Parquet.jl#109]
Steps to reproduce

Version:
`Installed Parquet ───────────────── v0.5.2`

Code to reproduce:
```
using Parquet
Parquet.File
```

You should now see
`UndefVarError: File not defined`, 
which is weird because this is what the README says we should do

**Comment by xiaodaigh** [comment]
You should be using the latest release which is 0.7.

**Comment by sa-** [comment]
True, I installed this in a fresh env today, maybe I was relying on another package that needed a lower version?

Thanks!
