### ISSUE TITLE
Write is very slow due to call to Base.summarysize

### ISSUE THREAD

**Issue by altre** [JuliaIO/Parquet.jl#126]
Hi and thanks for working on reading and writing Parquet in Julia. We really needed this!

I have a large DataFrame which in uncompressed csv is about 750mb. Writing this as parquet is very slow. 
This seems to be largely caused by the call to Base.summarysize which takes about 11 minutes (!) for my dataframe.

**Comment by tanmaykm** [comment]
Maybe calling `summarysize` only on a smaller sample instead of the entire table will be enough to do the writer chunk estimation. @xiaodaigh ?

**Comment by xiaodaigh** [comment]
> Writing this as parquet is very slow.

Yeah. This parquet writer just works but is not at all optimized! Apologies!

@tanmaykm I can't promise anytime at the moment due to family commitments. So no guarantee as to when this can be fixed!

**Comment by tanmaykm** [comment]
Fixed with #140
