### ISSUE TITLE
Zstd for Parquet reader

### ISSUE THREAD

**Issue by ldsands** [JuliaIO/Parquet.jl#39]
I would love to see the [zstandard](http://facebook.github.io/zstd/) implemented for parquet reading here. [I did a short blog](https://dev.to/ldsands/snappy-vs-zstd-for-parquet-in-pyarrow-9g0) talking about the benefits of this. The TLDR is that zstandard is just as fast as snappy but takes about 2/3 the amount of space that snappy does. I think it would be useful to have this implemented in this package.

Edit: Upon further digging around:

I've looked at the code and although I don't understand much of it I think that just adding the [Julia implimation of the Zstd codec](https://github.com/bicycle1885/CodecZstd.jl) Using ParFile works for Zstd compressed files unfortunately I don't really know what to do from there. I've looked around and I cannot tell where you determine the codec to use. If I figure it out I may try and create a pull request.

**Comment by ldsands** [comment]
I'm trying to add all of the changes needed to open zstd compressed files. Bare with me I have not really used git or github before so I'm trying to figure out what I'm doing.

**Comment by ldsands** [comment]
Okay I think I've done everything I need to support parquet files that have been compressed using zstd. Please let me know your thoughts on my pull request.

**Comment by xiaodaigh** [comment]
added in #65 and released in 0.4

**Comment by xiaodaigh** [comment]
Please close this as it's supported now
