### ISSUE TITLE
RecCursor does not seem to be working

### ISSUE THREAD

**Issue by Sarah-W** [JuliaIO/Parquet.jl#46]
![image](https://user-images.githubusercontent.com/5178718/78315749-66f63600-75ba-11ea-940b-0ea80a828f26.png)

**Comment by Sarah-W** [comment]
![image](https://user-images.githubusercontent.com/5178718/78398543-bfc3de00-764f-11ea-93ea-2bef499d8b9c.png)

So this seems to be the root of the problem - Our parquet file contains a boolean. I'm gonna have a go at fixing this later, but I am not the world's best .jl dev. 

If it makes any difference, we are trying to use this to streamline our data workflow in response to the current pandemic. It would really help us if this could be fixed.

**Comment by ViralBShah** [comment]
@tanmaykm can we fix this on priority?

**Comment by tanmaykm** [comment]
I'll look into it.
It will be good to have a parquet file to test this against.

**Comment by Sarah-W** [comment]
I am very sorry, but I cannot share the file we are working with as it contains sensitive data. I can do testing for you on it, and I will see if I can get a non-sensitive parquet for you to use.

**Comment by tanmaykm** [comment]
Thanks, I understand. It will be great if you could share a non-sensitive parquet file. The parquet specification seems quite sparse on this topic for booleans. I am trying to look into other sources, but I may finally need to reverse engineer the implementation.

**Comment by blairn** [comment]
I'm on it, I'll have a parquet soon.

**Comment by blairn** [comment]
ok, there we go, this gz contains a VERY simple parquet, and 2 lines, and the CSV in there is the decoded version of it.

Enjoy.

[all.tar.gz](https://github.com/JuliaIO/Parquet.jl/files/4435602/all.tar.gz)

**Comment by tanmaykm** [comment]
I have now put up a [PR](#48) to address this.
Could you try this on your data and check if it works?
I shall merge and tag a release once the CI passes.

**Comment by Sarah-W** [comment]
Checking now

**Comment by Sarah-W** [comment]
And it looks like its working! Thank you so very much!

**Comment by blairn** [comment]
You people are amazing!!!!
You have no idea what kind of difference this makes. We were having to fire up spark clusters just to convert this data to a CSV. 

Being able to handle it in Julia just makes everything so VERY much better.

**Comment by ViralBShah** [comment]
Please just ping us on anything you need without hesitation.

**Comment by blairn** [comment]
Seriously, you have no idea how much work you have saved us on a daily basis with this.
The workflows we had were horrible. The Julia community in general has been amazing, and you lot have been super amazing.

Time to go and automate all of the things.

**Comment by tanmaykm** [comment]
Great! The PR to register a new version is here: https://github.com/JuliaRegistries/General/pull/12349. 

Unfortunately it has failed for what looks like some unrelated issue. Someone should be looking at that soon. I will update here once that is sorted out.

**Comment by tanmaykm** [comment]
New version (v0.3.2) is registered now.

**Comment by xiaodaigh** [comment]
In case, people have issue reading Parquet files I have a version that can read many of the parquet that can't be read by Parquet.jl at the moment.

https://github.com/xiaodaigh/Diban.jl/blob/master/README.md

So worth a try if you run into issues. I promise to make a PR into this when I am done with the code. I prefer having just a Parquet.jl repo for all parquet stuff.
