### ISSUE TITLE
Data Page read is correct?

### ISSUE THREAD

**Issue by xiaodaigh** [JuliaIO/Parquet.jl#60]
https://github.com/JuliaIO/Parquet.jl/blob/b68e6af6ed6c67010a82b7e74b589c5ca94a80b6/src/reader.jl#L253-L263

In the code referenced above the data is read definition level then repetition and then encoded values.

This is different from [the documentation](https://github.com/apache/parquet-format) which is ordered repetition level then definition and then encoded

![image](https://user-images.githubusercontent.com/4497189/80978222-1ef05a80-8e69-11ea-8150-86e79830369e.png)

Which is correct?

**Comment by tanmaykm** [comment]
The order in the code is correct, i.e. definition levels followed by repetition levels.

**Comment by wesm** [comment]
Here's where we assemble the data page in the official C++ library

https://github.com/apache/arrow/blob/master/cpp/src/parquet/column_writer.cc#L686

```c++
  // Concatenate the encoded levels and values into one buffer
  void ConcatenateBuffers(int64_t definition_levels_rle_size,
                          int64_t repetition_levels_rle_size,
                          const std::shared_ptr<Buffer>& values, uint8_t* combined) {
    memcpy(combined, repetition_levels_rle_->data(), repetition_levels_rle_size);
    combined += repetition_levels_rle_size;
    memcpy(combined, definition_levels_rle_->data(), definition_levels_rle_size);
    combined += definition_levels_rle_size;
    memcpy(combined, values->data(), values->size());
  }
```

Here is what the Parquet format says 

![image](https://user-images.githubusercontent.com/329591/82696265-4ba7be80-9c2c-11ea-9170-0f22140120f0.png)

**Comment by tanmaykm** [comment]
Ah! Yes indeed. Thanks @wesm.
PR here: #86
