### ISSUE TITLE
add example how to use colcursor

### ISSUE THREAD

**Issue by xiaodaigh** [JuliaIO/Parquet.jl#76]

**Comment by tanmaykm** [comment]
You could see an example of using `ColCursor` in the `RecordCursor` implementation. It may not make sense to use it on nested schemas, but may be useful with flat schemas.

**Comment by xiaodaigh** [comment]
> an example of using `ColCursor` in the `RecordCursor` implementation

kinda tough to get. anyway i will close it. 

Doesn't seem to be user-facing type of functions.

One thing I can't answer with Parquet.jl is that how do I read a full column? It's very hard to figure it out despite parquet being a columnar-format. The examples in the readme seems to be for reading it row-by-row.
