### ISSUE TITLE
Why `ParFile` instead of `ParquetFile`?

### ISSUE THREAD

**Issue by nalimilan** [JuliaIO/Parquet.jl#99]
`ParFile` is much less explicit than `ParquetFile`. Saving 4 characters doesn't sound worth it IMHO.

**Comment by quinnj** [comment]
I'm a big fan of doing `Parquet.File` as well, because the module name is already part of the name here.

**Comment by xiaodaigh** [comment]
Can't agree more

**Comment by nalimilan** [comment]
Indeed, that way we would have the same convention as `CSV.File` and `Arrow.Table`.
